version: '3'
services:
  varnish:
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - app:/app
  http:
    # https://hub.docker.com/r/jordimartin/mmock/
    image: jordimartin/mmock
    ports:
      - "8083:8083"
      - "8084:8084"
    volumes:
      - "./http:/config"


volumes:
    app:
